"""Context compaction — anchored iterative summarization for CLI sessions."""

from __future__ import annotations

from typing import TYPE_CHECKING

from decepticon.ui.cli.console import console

if TYPE_CHECKING:
    from decepticon.core.streaming import StreamingEngine


def _build_session_summary(messages: list) -> str:
    """Build an anchored iterative summary of the conversation.

    Implements the context-compression "anchored iterative summarization" pattern:
    structured summaries with explicit sections force preservation of critical
    information (artifact trail, decisions, findings) that would otherwise be
    silently lost during compression.
    """
    from langchain_core.messages import AIMessage, HumanMessage, ToolMessage

    targets: list[str] = []
    commands_run: list[str] = []
    findings: list[str] = []
    files_created: list[str] = []
    user_requests: list[str] = []

    for msg in messages:
        if isinstance(msg, HumanMessage):
            content = str(msg.content)
            if content and len(content) < 200:
                user_requests.append(content)

        elif isinstance(msg, AIMessage):
            text = str(msg.content) if isinstance(msg.content, str) else ""
            # Extract findings mentions
            for keyword in ["CRITICAL", "HIGH", "MEDIUM", "exposed", "vulnerable", "takeover"]:
                if keyword in text:
                    # Take the sentence containing the keyword
                    for line in text.split("\n"):
                        if keyword in line and len(line) < 200:
                            findings.append(line.strip())
                            break

            # Extract tool calls
            if hasattr(msg, "tool_calls") and msg.tool_calls:
                for tc in msg.tool_calls:
                    cmd = tc.get("args", {}).get("command", "")
                    if cmd and len(cmd) < 150:
                        commands_run.append(cmd)
                    # Detect file creation
                    if "-oN " in cmd or "-o " in cmd or "> /workspace/" in cmd:
                        for part in cmd.split():
                            if part.startswith("/workspace/"):
                                files_created.append(part)

        elif isinstance(msg, ToolMessage):
            content = str(msg.content)
            # Extract target IPs/domains from tool output
            import re

            ips = re.findall(r"\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b", content[:2000])
            for ip in ips[:5]:
                if ip not in targets:
                    targets.append(ip)

    # Build structured summary
    lines = ["## Session Summary (auto-generated by /compact)\n"]

    if user_requests:
        lines.append("### User Requests")
        for req in user_requests[-5:]:  # Last 5 requests
            lines.append(f"- {req}")
        lines.append("")

    if targets:
        lines.append("### Targets Discovered")
        for t in list(dict.fromkeys(targets))[:10]:  # Deduplicated, max 10
            lines.append(f"- {t}")
        lines.append("")

    if commands_run:
        lines.append(f"### Commands Run ({len(commands_run)} total)")
        for cmd in commands_run[-10:]:  # Last 10 commands
            lines.append(f"- `{cmd}`")
        lines.append("")

    if findings:
        lines.append("### Key Findings")
        for f in list(dict.fromkeys(findings))[:10]:
            lines.append(f"- {f}")
        lines.append("")

    if files_created:
        lines.append("### Files in /workspace/")
        for f in list(dict.fromkeys(files_created)):
            lines.append(f"- {f}")
        lines.append("")

    return "\n".join(lines)


def compact_context(engine: StreamingEngine, config: dict) -> None:
    """Compact conversation context using anchored iterative summarization.

    Two-phase compaction (context-compression pattern):
    1. Generate structured summary of the conversation (preserving artifact trail)
    2. Replace verbose tool outputs with compact observation masks
    """
    from langchain_core.messages import AIMessage, SystemMessage, ToolMessage

    from decepticon.core.streaming import MASK_THRESHOLD, _mask_observation

    try:
        state = engine.agent.get_state(config)
        if not state or not hasattr(state, "values"):
            console.print("[yellow]No conversation state to compact.[/yellow]")
            return

        messages = state.values.get("messages", [])
        if len(messages) < 6:
            console.print("[dim]Conversation too short to compact.[/dim]")
            return

        # Phase 1: Build anchored summary of the full conversation
        summary = _build_session_summary(messages)

        # Phase 2: Mask verbose tool outputs (keep last 2 turns)
        recent_boundary = max(0, len(messages) - 6)
        masked_count = 0
        tokens_saved = 0

        for i in range(recent_boundary):
            msg = messages[i]
            if not isinstance(msg, ToolMessage):
                continue
            content = str(msg.content)
            if len(content) <= MASK_THRESHOLD:
                continue
            if content.startswith("[Observation masked"):
                continue

            original_len = len(content)
            msg.content = _mask_observation(content, "bash", {})
            tokens_saved += original_len - len(msg.content)
            masked_count += 1

        # Inject summary as first message after system prompt
        # Find insertion point (after any existing summary)
        insert_idx = 0
        for i, msg in enumerate(messages):
            if isinstance(msg, SystemMessage) and "Session Summary" in str(msg.content):
                messages.pop(i)  # Remove old summary
                insert_idx = i
                break
            if isinstance(msg, (AIMessage, ToolMessage)):
                insert_idx = i
                break

        if summary.count("\n") > 5:  # Only inject if summary has content
            messages.insert(insert_idx, SystemMessage(content=summary))

        if masked_count > 0 or summary.count("\n") > 5:
            engine.agent.update_state(config, {"messages": messages})
            console.print(
                f"[green]Compacted: {masked_count} tool outputs masked "
                f"(~{tokens_saved // 4:,} tokens freed), "
                f"session summary injected.[/green]"
            )
        else:
            console.print("[dim]Nothing to compact — context is already lean.[/dim]")

    except Exception as e:
        console.print(f"[yellow]Compaction failed: {e}[/yellow]")
